### ISSUE TITLE
Spy.off desired output is to remove a spy (regardless of whether it exists?)

### ISSUE THREAD

**Issue by ghostsquad** [ryanong/spy#10]
https://github.com/ryanong/spy/blob/master/lib/spy/subroutine.rb#L321

It seems that the desired behavior of `Spy.off` is to remove a spy (or do nothing, if the spy doesn't exist). What use case is there to raise an error if there was no spy on a method?

**Comment by ryanong** [comment]
I think the original intention was to raise. but I can see how it would be more useful to make it not.

**Comment by ghostsquad** [comment]
Right, but why raise? What's the point of raising an exception when removing a spy if there is no spy to remove?

**Comment by ryanong** [comment]
Because then you shouldn't be removing it and remove the code to remove the spy that doesn't exist. Make the test less noisy. I removed the raise though
