### ISSUE TITLE
Minimum supported Ruby version should be raised to 2.5

### ISSUE THREAD

**Issue by vlad-pisanov** [ryanong/spy#20]
Currently, the docs state that the gem is compatible with Ruby >= 2.1, whereas it actually needs Ruby >= 2.5

A line like `Spy.on(String, :freeze)` will fail in earlier versions of Ruby with
```
Minitest::UnexpectedError:         NoMethodError: private method `alias_method' called for #<Class:String>
```

This is due to `Module#alias_method` being changed from private to public in version 2.5:
https://apidock.com/ruby/v2_4_6/Module/alias_method
https://apidock.com/ruby/v2_5_5/Module/alias_method

**Comment by ryanong** [comment]
fixed in #19 19
