### ISSUE TITLE
undefined method present for {}

### ISSUE THREAD

**Issue by HoneyryderChuck** [ryanong/spy#31]
Hi, [some test builds](https://gitlab.com/os85/httpx/-/jobs/3510064812)  using this gem started failing due to an error caused by [this line](https://github.com/ryanong/spy/blob/master/lib/spy/subroutine.rb#L214).

I'm not sure what caused this, given that it's been like this for a while, but for what it's worth, Hash does not respond to `.present?`, unless activesupport is loaded. So either another ge used by my tests was loading it and caused this check to pass, or activesupport used to be a dependency from `spy` and now it isn't. 

Nevertheless, I'd rather not recomend you to add activesupport, so could this check be rewritten using ruby standard API?

**Comment by ryanong** [comment]
oh good call will update it

**Comment by ryanong** [comment]
should be fixed in the latest release
