### ISSUE TITLE
Cannot spy on methods with named parameters

### ISSUE THREAD

**Issue by wesm-outreach** [ryanong/spy#9]
## Repro Steps
```
require 'spy'

class Foo
  def do_stuff(a, b: nil)
    puts("hello")
  end
end

f = Foo.new

Spy.on(f, :do_stuff)

f.do_stuff('val1', b: 'val2')
```

## Expected Results
no error, can investigate call arguments (including a hash of named arguments)

## Actual Results
error
```
/Users/wes/.rvm/gems/ruby-2.3.3/gems/spy-0.4.5/lib/spy/subroutine.rb:266:in `check_arity!': wrong number of arguments (2 for 1) (ArgumentError)
	from /Users/wes/.rvm/gems/ruby-2.3.3/gems/spy-0.4.5/lib/spy/subroutine.rb:204:in `invoke'
	from /Users/wes/.rvm/gems/ruby-2.3.3/gems/spy-0.4.5/lib/spy/subroutine.rb:231:in `block in override_method'
	from test.rb:13:in `<main>'
```

**Comment by ryanong** [comment]
uhhhhgg. I really need to update this to support ruby 2.2+

I'll try to make some time this weekend.

**Comment by ghostsquad** [comment]
@ryanong any update? I'd love to contribute to this project, but I'm afraid that the meta programming you've done to make this work is a bit beyond my ruby skills. :(

**Comment by Willigenburg** [comment]
@ryanong You still plan to update to a newer Ruby version? Keyword arguments / named parameters would be really nice!

**Comment by kleinjm** [comment]
Same issue here

**Comment by ryanong** [comment]
honestly I've been pretty unmotivated to work on projects outside of work. I would gladly accept and mentor anybody who is interested in submitting a patch.

The specific work that would need to be done would be adding named parameters support
here https://github.com/ryanong/spy/blob/master/lib/spy/subroutine.rb#L230
and here https://github.com/ryanong/spy/blob/master/lib/spy/subroutine.rb#L203
